# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'mishiesmunchies'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home',               url: ''}
- {name: 'About',              url: 'about'}
- {name: 'News',               url: 'news'}
- {name: 'Blog',               url: 'blog'}
- {name: 'Referrals',          url: 'referrals'}
- {name: 'FAQ',                url: 'faq'}
- {name: 'Menu',               url: 'menu'}
- {name: 'Order',              url: 'order'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://instagram.com/mishiesmunchies'}
- {icon: 'envelope', link:   'mailto:mishiesmunchies@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
